spring: 
  profiles: 
    active: 
    - dev
  
---
server:
  port: 9527

spring:
  profiles: dev
  application:
    name: css-api-gateway
  redis:
    host: 121.201.65.111
    port: 6079
    password: ahui123321
    timeout: 25000 
    clusterNodes: 121.201.65.111:7003
    clusterPassword: ahui123321
    isCluster: false
      

    
eureka:
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true 
    
zuul: 
  prefix: /znzj
  ignored-services: "*"
  routes: 
    user:
      serviceId: css-user-service
      path: /user-service/**
    analyzer: 
      serviceId: css-analyzer-service
      path: /analyzer-service/**
    inspect: 
      serviceId: css-inspect-service
      path: /inspect-service/**
    statistics: 
      serviceId: css-statistics-service
      path: /statistics-service/**

  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 120000
          
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1  
  
sftp: 
  host: 121.201.65.111
  port: 6022
  username: root
  password: 123456
    
info: 
  app.name:  ${spring.application.name}
  company.name: www.xph.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
---

server:
  port: 9527

spring:
  profiles: test
  application:
    name: css-api-gateway
  redis:
    host: 192.168.1.79
    port: 6379
    password: ahui123321
    timeout: 25000 
    clusterNodes: 192.168.96.102:7001,192.168.96.102:7002,192.168.96.102:7003,192.168.96.102:7004,192.168.96.102:7005,192.168.96.102:7006
    clusterPassword: ahui123321
    isCluster: false

    
eureka:
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true 
    
zuul: 
  prefix: /znzj
  ignored-services: "*"
  routes: 
    user.serviceId: css-user-service
    user.path: /user-service/**
    analyzer.serviceId: css-analyzer-service
    analyzer.path: /analyzer-service/**
    inspect.serviceId: css-inspect-service
    inspect.path: /inspect-service/**
    statistics.serviceId: css-statistics-service
    statistics.path: /statistics-service/**
  host: 
    socket-timeout-millis: 120000 
    connect-timeout-millis: 120000
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 120000

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1  
  
sftp: 
  host: 192.168.1.79
  port: 22
  username: root
  password: 123456
  
    
info: 
  app.name:  ${spring.application.name}
  company.name: www.xph.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
