
spring: 
  profiles: 
    active: 
    - dev
    
---
server:
  port: 8783
  
eureka:
  instance: 
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.application.name}:${server.port}
    ##续约到期时间10秒，默认是90秒
    #lease-expiration-duration-in-seconds: 10
    ##续约更新时间间隔设置5秒，m默认30s
    #lease-renewal-interval-in-seconds: 5
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/

##调整格隔离策略,防止feign相互之间调用丢失参数      
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

info: 
  app.name: ${spring.application.name}
  company.name: www.xpj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
spring: 
  profiles: dev
  application:
    name: css-inspect-service
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     platform: mysql
     url: jdbc:mysql://121.201.65.111:6306/ellison?useUnicode=true&characterEncoding=utf-8
     username: root
     password: 123456
  redis:
    host: 121.201.65.111
    port: 6079
    password: ahui123321
    timeout: 25000 
    clusterNodes: 121.201.65.111:7003
    clusterPassword: ahui123321
    isCluster: false

mybatis: 
  type-aliases-package: com.znzj.model
  mapper-locations: classpath:mapper/**/*.xml
  
inspect:
  ability:
    wav.url: http://121.201.65.111:6101/ability/offlineasr
    v3.url: http://121.201.65.111:6101/ability/offlineasr
  analyzer.url: http://121.201.65.111:7000
  dialogDate: 2
  datDir:  /home/dat
  fileRre:  TRECORDINFO
  limitSecond: 18000000
  audioRootDir: /sz_record/
  
sftp:
  username:  root
  password:  123456
  host: 121.201.65.111
  port: 6022

dialog:
  sftp:
    username:  root
    password:  123456
    host: 121.201.65.111
    port: 6022

---
server:
  port: 8783
  
eureka:
  instance: 
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.application.name}:${server.port}
    ##续约到期时间10秒，默认是90秒
    #lease-expiration-duration-in-seconds: 10
    ##续约更新时间间隔设置5秒，m默认30s
    #lease-renewal-interval-in-seconds: 5
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/

##调整格隔离策略,防止feign相互之间调用丢失参数      
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

info: 
  app.name: ${spring.application.name}
  company.name: www.xpj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
spring: 
  profiles: test 
  application:
    name: css-inspect-service
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     platform: mysql
     url: jdbc:mysql://localhost:3306/ellison?useUnicode=true&characterEncoding=utf-8
     username: root
     password: 123456
  redis:
    host: 192.168.1.79
    port: 6379
    password: ahui123321
    timeout: 25000 
    clusterNodes: 192.168.96.102:7001,192.168.96.102:7002,192.168.96.102:7003,192.168.96.102:7004,192.168.96.102:7005,192.168.96.102:7006
    clusterPassword: ahui123321
    isCluster: false

mybatis: 
  type-aliases-package: com.znzj.model
  mapper-locations: classpath:mapper/**/*.xml
  
inspect:
  ability:
    wav.url: http://localhost:20101/ability/offlineasr
    v3.url: http://localhost:20101/ability/offlineasr
  analyzer.url: http://localhost:8000
  dialogDate: 2
  datDir:  /home/dat
  fileRre:  TRECORDINFO
  limitSecond: 18000000
  audioRootDir: /sz_record/
  
sftp:
  username:  root
  password:  123456
  host: 127.0.0.1
  port: 22
  
dialog:
  sftp:
    username:  root
    password:  123456
    host: 127.0.0.1
    port: 22
